### ISSUE TITLE
no access to settings in Venom/can't change language

### ISSUE THREAD

**Issue by mycomachine** [randallspicher/skin.lyrebird.rmod#22]
Not sure if I'm just missing it but I've looked everywhere and need to change the skin to change the language. Should be a gear icon somewhere.

**Comment by randallspicher** [comment]
What is "Venom"?

Are you referring to changing the language of the UI? 
Settings -> Interface   ->  Regional -> Language

**Comment by randallspicher** [comment]
"Venom" appears to be in the banned plugin list.  So, I cannot help with that.
https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons
