### ISSUE TITLE
Movie and series library statistics do not show up

### ISSUE THREAD

**Issue by Vergil365** [randallspicher/skin.lyrebird.rmod#26]
movie and series library statistics do not show up in the main menu of mimic-lr.
i tested it on macos and android.

here are my settings:
![movie statics settings](https://user-images.githubusercontent.com/88899662/166132364-6caa9ff2-2793-45c4-98dc-182b7e352c63.png)

but there are no statistics:
![movie statics](https://user-images.githubusercontent.com/88899662/166132345-44ada1ba-1ef9-4361-a4f0-ccebc3315110.png)

**Comment by randallspicher** [comment]
1. What are all of the statistics that should be displayed? 
2. Would you want to see this replace the "current location" in the very top?  (the "Home" in your image), or would you want to see it in the notifications area below it (the space before the menus start, where the "now playing" displays on the right side, and (on the left) you see things like the indexing progress displayed)

**Comment by Vergil365** [comment]
Thank you for asking me :)
2. I would like to have it like this picture a made, but with the same fonts as the "Home".

![Menu neu](https://user-images.githubusercontent.com/88899662/166296970-4f97e6a3-c0cd-4b81-b608-844b980b1338.png)
 
1. I always used the following 3 statistics (pictures from the original mimic)

Movie statistics
![movies](https://user-images.githubusercontent.com/88899662/166297452-b4577974-e4fa-4fe4-9bd4-022216c8d610.png)

Series statistics
![serien](https://user-images.githubusercontent.com/88899662/166297495-82de94a0-9102-4c01-8afb-c391f186b044.png)

Settings statistics
![settings](https://user-images.githubusercontent.com/88899662/166297535-f367eed4-628b-450a-af18-332fa8c7b829.png)

**Comment by randallspicher** [comment]
Info-Line data seems to have gotten dropped somewhere along the way.
Should probably go into the "info" area under the header, where the notices show up (with appropriate visibility settings to hide them when notices are showing)

**Comment by Vergil365** [comment]
i dont understand where you want to put it?
the setting for visibility is already there in the skin/mainmenu settings (shown in the picture of my first post).
it would be really nice to see how many of my movies and series i have watched/unwatched in my collection.
the main menu is the best place to put this i think.

**Comment by randallspicher** [comment]
fixed in 8.2.1

**Comment by Vergil365** [comment]
@randallspicher 
thank you very much, its so nice to have it back :DD 
i missed it so badly.
is it to much to ask to reposition it to the top bar, to make it more readable?
Like in the following picture but with the same font like "Home" in the top bar:

![](https://user-images.githubusercontent.com/88899662/166296970-4f97e6a3-c0cd-4b81-b608-844b980b1338.png)
