### ISSUE TITLE
Watched status icon is almost completly white

### ISSUE THREAD

**Issue by Vergil365** [randallspicher/skin.lyrebird.rmod#27]
the watched status is almost completly white

<img width="155" alt="watched" src="https://user-images.githubusercontent.com/88899662/166132317-d4855c63-9c63-435e-bdfe-357c8019c605.png">

this is how it should look like:
<img width="204" alt="watched kodi v18" src="https://user-images.githubusercontent.com/88899662/166133294-8745272a-d113-4908-8432-0e2e11064d6e.png">

i tested it on macos and android.

**Comment by randallspicher** [comment]
fixed in latest beta. It should now use the focus color (to match the "in progress" color)

**Comment by Vergil365** [comment]
thank you very much, you are the best! :DD
But where can i download the beta version?
