### ISSUE TITLE
Record button not pushable in using PVR

### ISSUE THREAD

**Issue by nagysifa** [randallspicher/skin.lyrebird.rmod#4]
First of all THANX for keeping alive this great skin!

I am using Your adaptation of the lyrebird skin on Windows 10 ( x64 and x86 ), and on Libreelec ( RPI2 and RPI3 ) with KODI 18.9.
The isue I have is with PVR Addon "Enigma2 Client" - using it with this skin, the RECORD button is "greyed out" - can not push it from full screen. I can make a record from channel list -> context menu - > record.
The same button is working from other skins ( tried it with Rapier and Estuary ).

Could You please look into this ?
Kind regards : Zoltan.

Record Button not pushable from lyrebird.rmod :
![Rec-Button-skin lyrebird rmod](https://user-images.githubusercontent.com/14113441/108839071-d7dc7d00-75d4-11eb-8df6-d899cc8bc38b.jpg)
Record Button pushable from estuary :
![Rec-Button-estuary](https://user-images.githubusercontent.com/14113441/108839089-ddd25e00-75d4-11eb-978f-a9b2b9308781.jpg)
Record working from Channel List - > Context Menu :
![Rec-From-Context-Menu-skin lyrebird rmod](https://user-images.githubusercontent.com/14113441/108839102-e2971200-75d4-11eb-83fb-c7f61f7cbfac.jpg)

**Comment by nagysifa** [comment]
My bad. After Your latest update it works. THX

**Comment by randallspicher** [comment]
Actually, I never even noticed the record button in the OSD until you pointed it out.  I wasn't paying attention to the email to notice it was a github issue rather then a direct email, or I would have updated the issue here...
