### ISSUE TITLE
Option to "undim" non-focused covers on all views (similar to what keibertz view has)

### ISSUE THREAD

**Issue by Vergil365** [randallspicher/skin.lyrebird.rmod#7]
Hallo randallspicher,
sorry that i post this in the issue section, but when i was trying to pull a request i've got to the other fork pages.
Thank you very much for still supporting that awesome skin for kodi.
It's my favorite skin of all time, but there is just one thing that disturbs me about it.
All non selected covers of movies and tv shows are grayed out.
I was thinking of modding the skin settings that the covers would show in normal colors even if it's not selected.
But i don't know which line i have to change to prevent that grayed out covers.
Could you please help me?

**Comment by randallspicher** [comment]
on the various view templates, you will see an &lt;itemlayout&gt; container, and a corresponding &lt;focusedlayout&gt; container (should be right next to each other.  those define how to display the individual items in the list.  in most itemlayout sections, there's a second image underneath the primary one which looks something like this:

```
 						<control type="image">
							<top>6</top>
							<left>6</left>
							<width>230</width>
							<height>345</height>
							<texture border="5">overlays/diffuse-overlay.png</texture>
						</control>

```
these "overlay" images are transparent images that get displayed on top of the original one, to "grey it out".  if you comment out that second image control in &lt;itemlayout&gt;, it would stop being greyed out.   Note that within focuseditem, there's usually some animation business going on to make the "grey" fade in and out as you navigate around, which you'd probably want to remove as well to get rid of the blinky effect when scrolling around.

I could, potentially, revise how this greyed out effect works, and make the transparency level adjustable (and/or disable-able) I did something sort of similar on the music screens to let the visualization "bleed through" the cover/fanart, where the transparency level can be adjusted to personal preference) 

I'd note there's a *lot* of item lists scattered around to deal with.  (some views have half a dozen or more, for handling different types of images you may have selected to display in the list)

**Comment by Vergil365** [comment]
thank you very much for your help :D
I deleted the row
"<texture border="5">overlays/diffuse-overlay.png</texture>"
in the views i use and now it works.
I dont see any animations^^
This feature would be very nice, in that case i dont have to modify the skin everytime i update it^^
Anyway i am happy now :)

**Comment by randallspicher** [comment]
Added to latest beta
