### ISSUE TITLE
CoverFlow View (in matrix) showing thumbnails instead of posters

### ISSUE THREAD

**Issue by nagysifa** [randallspicher/skin.lyrebird.rmod#8]
Hello again randallspicher!

Getting ready to migrate to 19.1 from 18.9 ... I would like to stay on "skin.lyrebird.rmod" if possible.
There is an anomaly I cant seem to set ... I like my Movies and Series to be displayed in "Coverflow" mode. For some reason on Matrix there is a thumbnail displayed instead of the cover pictures :

KODI 18.9
[![KODI-18-9-Coverflow.jpg](https://i.postimg.cc/fR4cFv09/KODI-18-9-Coverflow.jpg)](https://postimg.cc/9rpwwZbm)

KODI 19.1
[![KODI-19-1-Coverflow.jpg](https://i.postimg.cc/fRxch0xg/KODI-19-1-Coverflow.jpg)](https://postimg.cc/rDw01sZS)

Is there some setting I dont know about ? ( both installations are from scratch, all settings are set the same, and only the apropriate skin ( leia and matrix ) are installed. Both installations are using the same advancedsettings.xml file - connected to the same mysql database ( library ).

Thanx in advance for any info on this matter!

**Comment by randallspicher** [comment]
The "poster_icon" include uses ListItem.Icon 
In kodi 19, the meaning of ListItem.Icon changed,  in 18, ListItem.Icon would return a poster as a fallback if there was no actual thumbnail image defined.  Now it is supposed to return, and I quote:
"Shows the thumbnail (if it exists) of the currently selected item in a list or thumb control. If no thumbnail image exists, it will show the default icon. "

The relevant skin code needs to change to grab ListItem.art(poster) instead. 

I updated that for a bunch of the other views, but never really used coverflow myself, so missed it.

**Comment by randallspicher** [comment]
I pushed an update.  Also fixed kibertz and arcade views, as well as properly deal with seasons and sets.

**Comment by nagysifa** [comment]
I can confirm, it works now on Matrix with kiebertz, arcade, or coverflow Views as it was on Leia!

Thanx for the quick replay and quick fix!
